server:
  port: 8099


security:
  require-ssl: true

spring:
  application:
    name: search-service
  data:
    mongodb:
      database: topic
      host: localhost
      port: 27017
  rabbitmq:
    host: localhost
    port: 5672
jsa:
  rabbitmq:
    queue: jsa.queue1
    exchange: jsa.direct1
    routingkey: jsa.routingkey1
jsb:
  rabbitmq:
    queue: jsb.queue
    exchange: jsb.direct
    routingkey: jsb.routingkey

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8093/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'
      expose: '*'

