server:
  port: 8081
spring:
  data:
    neo4j:
      username: neo4j
      password: marvel
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  application:
    name: recommendation-query-service

questionAndAnswerUrl: http://localhost:8090/api/v1/

jsf:
  rabbitmq:
    queue: jsf.queue1
    exchange: jsf.direct1
    routingkey: jsf.routingkey1
jst:
  rabbitmq:
    queue: jst.queue1
    exchange: jst.direct1
    routingkey: jst.routingkey1


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8093/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'
      expose: '*'