server:
  port: 8080
  rabbitmq:
    host: localhost
    port: 5672
spring:
  data:
    neo4j:
      username: neo4j
      password: marvel
  application:
    name: recommendation-command-service

jse:
  rabbitmq:
    queue: jse.queue1
    exchange: jse.direct1
    routingkey: jse.routingkey1
jsf:
  rabbitmq:
    queue: jsf.queuereg
    exchange: jsf.directreg
    routingkey: jsf.routingkeyreg

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8093/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'
      expose: '*'