server:
  port: 8094
spring:
  cache:
    type: redis
    redis:
      time-to-live: 600000
  redis:
    port: 6379
    host: localhost
management:
  endpoints:
    web:
      exposure:
        include: '*'
      expose: '*'
